# Generated by Django 4.1 on 2022-09-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, verbose_name='コメント')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='経度')),
            ],
        ),
    ]
